#!/usr/bin/env bash
#This script displays the PID and process name of processes containing the word "bash"
for pid in /proc/[0-9]*/status; do
	if grep -qi "^Name:.*bash" "$pid"; then
		echo "$(basename "$(dirname "$pid")") $(grep -i "^Name:" "$pid" | awk '{print $2}')"
	fi
done
